### ISSUE TITLE
您好，怎么支持外接显示器呢。我的电脑和你的差不多。

### ISSUE THREAD

**Issue by whxcode** [war1644/MSI-GS66-Stealth-OC-Hackintosh#1]
![硬件参数](https://user-images.githubusercontent.com/44012914/202778703-b176d8fc-e09e-40b9-a6dc-b8e0061e8d0e.png)

**Comment by war1644** [comment]
因为gs66的hdmi和雷电都是直连在gpu上的。唯一的办法就是买个DisplayLink，走剩下的那个type-c口。
