### ISSUE TITLE
好兄弟，怎么联系你啊，能不能帮我提取一个vbios出来啊

### ISSUE THREAD

**Issue by look4uz** [war1644/MSI-GS66-Stealth-OC-Hackintosh#2]
我手贱给显卡vbios给刷废了，，好兄弟你是GS66 10UG 093这个型号嘛 ，能帮我提取一下嘛，很简单的就用GPUZ点那个vbios版本旁边那个分享的按钮就行，

**Comment by void2code** [comment]
qq群 1104475444
